/*
 * Project Euler #2 by Josh Oldenburg, 12/1/2014
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>
#include <stdint.h>

int main() {
	uint32_t sum = 0;
	uint32_t prev1 = 1;
	uint32_t prev2 = 1;

	/*
	 * Iteration 1: fibonacci = 1, fibb = 1 + 1 = 2, prev1 = 1, prev2 = fib = 2
	 * Iteration 2: fibonacci = 2, fibb = 1 + 2 = 3, prev1 = 2, prev2 = fib = 3
	 * Iteration 3: fibonacci = 3, fibb = 2 + 3 = 5, prev1 = 3, prev2 = fib = 5
	 * ...
	 */
	for (uint32_t fibonacci = 1; fibonacci < 4e6; fibonacci = prev1 + prev2, prev1 = prev2, prev2 = fibonacci) {
		/* printf("fib %u, prev1 %u, prev2 %u, sum %u\n", fibonacci, prev1, prev2, sum); */
		if (fibonacci % 2 == 0) sum += fibonacci;
	}

	printf("%u", sum);
	return 0;
}
